### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by elamperti** [MarlinFirmware/MarlinDocumentation#18]
When I enter the page [using HTTPS](https://marlinfirmware.github.io/MarlinDocumentation/), stylesheets and scripts fail to load because they are requested over HTTP.

**Comment by jbrazio** [comment]
@elamperti thank you for the report, this is an hard one to tackle properly due to two reasons:
- Github pages does not support `https` for custom domains
- We use the custom domain `marlinfw.org` as the official entry point for the documentation

As `https` is only supported by Github pages for `*.github.io` domains this causes the mixed content warning and, in some newer browsers, stylesheets not to be applied.
