### ISSUE TITLE
fork/exec C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc.exe: The filename or extension is too long.  Error compiling for board Arduino Mega or Mega 2560.

### ISSUE THREAD

**Issue by premaprilgithub** [MarlinFirmware/MarlinDocumentation#359]
Arduino: 1.8.13 (Windows 7), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Using library U8glib at version 1.19.1 in folder: C:\Users\Dhillon\Documents\Arduino\libraries\U8glib 

Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 

fork/exec C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc.exe: The filename or extension is too long.

Error compiling for board Arduino Mega or Mega 2560.

Above is the error message which i copied and pasted here. i am new to Marlin fw. Don't know how to resolve this issue. 
i am running arduino IDE on windows 7 64. 
Arduino mega 2560 with Ramps1.4
updated all the libraries but error still persist. 
Tried to search the web but no conclusion found. if anyone knows the solution please help me to upgrade my printer. Thanks and Regard.

**Comment by ellensp** [comment]
This is a Arduino IDE on Windows issue. Windows has a hard coded unchangeable max path/fork limit of 32K characters. Arduino IDE is written badly, when it attempts to link all the .o files together to form the final .bin file on large projects, such as Marlin, it generate one very long command that can easily exceed the windows limit.

There are a number of tricks to shorten the path under windows. 
Move marlin to root of drive, rename it to m
Delete unused parts of marlin such as unused HAL directories and unused display types. But this require in depth knowledge of how marlin works to know what is safe to remove.

Ultimately it is far better to use PlatformIO on vscode instead of Arduino IDE
PlatformIO only complies and links the code you need for your system, this avoids the Windows limitation. It also produces smaller binaries and is faster.
