### ISSUE TITLE
unable to compile using Arduino IDE on windows

### ISSUE THREAD

**Issue by khumanitzki** [MarlinFirmware/MarlinDocumentation#373]
compiler fails with error
avr-gcc: error: CreateProcess: No such file or directory

i think the command is truncated 
https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string
[Compile_error.txt](https://github.com/MarlinFirmware/MarlinDocumentation/files/5916518/Compile_error.txt)

**Comment by ellensp** [comment]
This is a Arduino IDE on Windows issue. Windows has a hard coded unchangeable max path/fork limit of 32K characters. Arduino IDE is written badly, when it attempts to link all the .o files together to form the final .bin file on large projects, such as Marlin, it generate one very long command that can easily exceed the windows limit.

There are a number of tricks to shorten the path under windows. 
Move marlin to root of drive, rename it to m
Delete unused parts of marlin such as unused HAL directories and unused display types. But this require in depth knowledge of how marlin works to know what is safe to remove.

Ultimately it is far better to use PlatformIO on vscode instead of Arduino IDE
PlatformIO only complies and links the code you need for your system, this avoids the Windows limitation. It also produces smaller binaries and is faster.
