### ISSUE TITLE
How to reserve gcodes that in development by Prusa or other firmware?

### ISSUE THREAD

**Issue by 3d-gussner** [MarlinFirmware/MarlinDocumentation#443]
I would like to reserve few gcodes which are in development to prevent issues using the same gcode in different firmware.
We have already few `Firmware dependent` and I would like to prevent it by "reserving" gcodes in the main 3D printed firmwares.

The [RepRap Gcode wiki](https://reprap.org/mediawiki/index.php?title=G-code&type=revision&diff=189575&oldid=189571) has been updated today. But I am not sure how to do that here and if that the Marlin team likes that approach.

**Comment by thinkyhead** [comment]
The RepRap wiki G-code page is the right place to add new codes that you want to reserve. But, it is a good idea to contact the Marlin project, the RepRapFirmware project, the Prusa Firmware project, the OctoPrint project, and the Repetier Host project, as needed, since all will be affected by any new proposals.
