### ISSUE TITLE
Bed leveling ender 3 v2

### ISSUE THREAD

**Issue by Hardmanpr** [MarlinFirmware/MarlinDocumentation#559]
I installed a bltouch with the spriter extruder then I installed the 2.1.3 MRiscoC 20240125 -01:18. I include de G29 on cura but when I print the printer just make the homing but not check the bed and I select 5 mesh point Y & Z I think maybe I forget something to configure.
Thank in advance
Att Raul
![Uploading IMG_3996.jpeg…]()

**Comment by thisiskeithb** [comment]
> I installed the 2.1.3 MRiscoC 20240125

You will need to open an issue in [MRiscoC's GitHub](https://github.com/mriscoc/Ender3V2S1) since we don't support forks here.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
